"""add column username

Revision ID: 986f34f1cd50
Revises: dd76798ba7c7
Create Date: 2025-02-17 12:00:17.282779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986f34f1cd50'
down_revision: Union[str, None] = 'dd76798ba7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analitic_control', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analitic_control', 'username')
    # ### end Alembic commands ###
