"""analitic control

Revision ID: b663ea011b11
Revises: 46b15ebaa69c
Create Date: 2025-02-10 15:17:10.975198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b663ea011b11'
down_revision: Union[str, None] = '46b15ebaa69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analitic_control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recdt', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('temperature', sa.REAL(), nullable=False),
    sa.Column('ph', sa.REAL(), nullable=False),
    sa.Column('color', sa.REAL(), nullable=False),
    sa.Column('chlorine', sa.REAL(), nullable=True),
    sa.Column('aluminum', sa.REAL(), nullable=False),
    sa.Column('turbidity', sa.REAL(), nullable=False),
    sa.Column('chlorides', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analitic_control')
    # ### end Alembic commands ###
